-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

--autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/themes/default/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.monitors")

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Source: ~/.config/hypr/themes/default/myprograms.conf — convert this file to Lua and ensure it is on Lua's package.path.
-- require("themes.default.myprograms")

--################
--## AUTOSTART ###
--################

-- Source: ~/.config/hypr/themes/default/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.autostart")

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

-- Source: ~/.config/hypr/themes/default/envvariables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.envvariables")

--##################
--## PERMISSIONS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Permissions/

-- Source: ~/.config/hypr/themes/default/permissions.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.permissions")

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

-- Source: ~/.config/hypr/themes/default/lookandfeel/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.lookandfeel.general")

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Source: ~/.config/hypr/themes/default/lookandfeel/decoration.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.lookandfeel.decoration")

-- https://wiki.hyprland.org/Configuring/Variables/#animations

-- Source: ~/.config/hypr/themes/default/lookandfeel/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.lookandfeel.animations")

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- workspace = w[tv1], gapsout:0, gapsin:0
-- workspace = f[1], gapsout:0, gapsin:0
-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]
-- windowrule = bordersize 0, floating:0, onworkspace:f[1]
-- windowrule = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

-- Source: ~/.config/hypr/themes/default/lookandfeel/dwindle.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.lookandfeel.dwindle")

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

-- Source: ~/.config/hypr/themes/default/lookandfeel/master.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.lookandfeel.master")

-- https://wiki.hyprland.org/Configuring/Variables/#misc

-- Source: ~/.config/hypr/themes/default/lookandfeel/misc.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.lookandfeel.misc")

--############
--## INPUT ###
--############

-- Source: ~/.config/hypr/themes/default/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.input")

--##################
--## KEYBINDINGS ###
--##################

-- Source: ~/.config/hypr/themes/default/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.keybinds")

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Source: ~/.config/hypr/themes/default/windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("themes.default.windowrules")
