-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = uwsm app -- /usr/bin/node /opt/waykey/run.js
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- exec-once = waydroid session start &
-- exec-once = [workspace 9 silent] waydroid app launch ua.itaysonlab.vkx
-- exec-once = linux-wallpaperengine --scaling fill --screen-root HDMI-A-1 --bg 202002033 --fps 30
-- exec-once = linux-wallpaperengine --scaling fill --screen-root eDP-1 --bg 202002033 --fps 30
-- exec-once = xwaylandvideobridge

hl.on("hyprland.start", function()
	hl.exec_cmd("nm-applet &")
	hl.exec_cmd("~/scripts/bash/run-swaync.sh &")
	hl.exec_cmd("waybar &")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("mpd &")
	hl.exec_cmd("~/scripts/bash/otdDaemonAutostart.sh &")
	hl.exec_cmd("vesktop", { workspace = "1 silent" })
	hl.exec_cmd("AyuGram", { workspace = "2 silent" })
	hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
	hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "Tokyonight-Dark"')
	hl.exec_cmd("hyprctl setcursor Fu-Xuan 32")
	hl.exec_cmd('gsettings set org.gnome.desktop.interface cursor-theme "Fu-Xuan"')
	hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 32")
	hl.exec_cmd("dconf write /org/gnome/desktop/interface/cursor-theme \"'Fu-Xuan'\"")
end)
