-- env = QT_QPA_PLATFORMTHEME,qt6ct

-- env = GTK_THEME,Tokyonight:dark

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("HYPRCURSOR_THEME", "Fu-Xuan")
hl.env("XCURSOR_THEME", "Fu-Xuan")

hl.env("XCURSOR_SIZE", "32")
hl.env("HYPRCURSOR_SIZE", "30")
hl.env("QT_CURSOR_SIZE", "30")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("SSH_AUTH_SOCK", "$XDG_RUNTIME_DIR/ssh-agent.socket")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("ECORE_EVAS_ENGINE", "wayland_egl")
hl.env("ELM_DISPLAY", "wayland")
hl.env("GDK_BACKEND", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("WLR_RENDERER", "vulkan")
hl.env("__NV_PRIME_RENDER_OFFLOAD", "1")

hl.env("GDK_SCALE", "1")

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

