-- https://wiki.hyprland.org/Configuring/Variables/#input
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

hl.gesture({
	fingers = 3,
	direction = "up",
	action = function() -- Функция, которая сработает ПОСЛЕ завершения жеста
		hl.dispatch(hl.dsp.exec_cmd("kitty"))
	end,
})

hl.gesture({
	fingers = 3,
	direction = "down",
	action = "close",
})

hl.gesture({
	fingers = 4,
	direction = "up",
	action = "fullscreen",
})

hl.gesture({
	fingers = 4,
	direction = "down",
	action = "fullscreen",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

hl.device({
	name = "opentabletdriver-virtual-artist-tablet",
	output = "HDMI-A-1",
})

hl.config({
	input = {
		kb_layout = "us,ru",
		kb_variant = "",
		kb_model = "",
		kb_options = "grp:alt_shift_toggle",
		kb_rules = "",
		follow_mouse = 2,
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = true,
		},
	},
	-- https://wiki.hyprland.org/Configuring/Variables/#gestures
	-- Example per-device config
	-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
})
