-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-1",
    mode = "highres@144",
    position = "0x0",
    scale = "1",
})

--monitor = HDMI-A-1,1920x1080@144,0x0,1
hl.monitor({
    output = "eDP-1",
    mode = "highres@144",
    position = "auto-right",
    scale = "1.2",
})

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
})

