-- Example windowrule
-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    match = {
        float = true,
        title = "^(Save As)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        float = true,
        title = "^(Discord)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        float = true,
        title = "^(Steam)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        float = true,
        title = "^(Minecraft)(.*)$",
    },
    center = true,
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({
    match = {
        title = "wine",
    },
    workspace = "special",
    pin = true,
})

hl.window_rule({
    match = {
        class = "^$",
        title = "Arknights",
    },
    no_blur = true,
    no_anim = true,
    opacity = "1.0 1.0 1.0",
    no_dim = true,
    no_shadow = true,
    force_rgbx = true,
})

hl.window_rule({
    match = {
        class = "^$",
        title = "Endfield",
    },
    no_blur = true,
    no_anim = true,
    fullscreen = true,
})

hl.window_rule({
    match = {
        class = "^(Waydroid).*",
    },
    opacity = "1.0 1.0 1.0",
    force_rgbx = true,
    no_dim = true,
    no_shadow = true,
})

-- windowrule = no_anim on, match:title ^(Endfield)$
-- windowrule = no_blur on, match:title ^(Endfield)$
-- windowrule = stay_focused on, match:title ^(Endfield)$
-- windowrule = fullscreen on, match:title ^(Endfield)$

-- windowrule = center, float, class:waydroid.ua.itaysonlab.vkx
-- windowrulev2 = , class:.*, title:^(Save As)(.*)$
